import { Schema, model, Document, Types } from 'mongoose';

// ─────────────────────────────────────────────
// Sub-document interfaces
// ─────────────────────────────────────────────

export interface ITag {
  name: 'backend' | 'security' | 'frontend' | 'urgent'; // NEEDS TO BE CHANGED
  visible: boolean;
}

export interface ICardNotifications {
  enabled: boolean | null; // null = inherit from user master toggle
  leadTime: number | null; // null = inherit user defaultLeadTime
  sentAt?: Date | null; // tracks when notification was last sent — null = not sent yet
}

export interface ICard {
  _id: Types.ObjectId;
  title: string;
  description?: string;
  priority?: 'low' | 'medium' | 'high' | 'urgent';
  order: number;
  tags: ITag[];
  dueDate?: Date;
  linkedEventId?: Types.ObjectId; // bidirectional → calendarEvents._id
  notifications?: ICardNotifications;
  createdAt: Date;
  updatedAt: Date;
}

export interface IColumn {
  id: string; // stable client-generated ID e.g. 'col_1'
  name: string;
  order: number;
  cards: ICard[];
}

// ─────────────────────────────────────────────
// Root board interface
// ─────────────────────────────────────────────

export interface IBoard extends Document {
  userId: Types.ObjectId;
  name: string;
  columns: IColumn[];
  createdAt: Date;
  updatedAt: Date;
}

// ─────────────────────────────────────────────
// Sub-schemas
// ─────────────────────────────────────────────

const TagSchema = new Schema<ITag>(
  {
    name: {
      type: String,
      enum: ['backend', 'security', 'frontend', 'urgent'], // NEED TO BE CHANGED
      required: true,
    },
    visible: { type: Boolean, required: true, default: false },
  },
  { _id: false },
);

const CardNotificationsSchema = new Schema<ICardNotifications>(
  {
    enabled: { type: Boolean, default: null }, // null = inherit
    leadTime: { type: Number, default: null }, // null = inherit
    sentAt: { type: Date, default: null }, // null = not sent yet, reset after dueDate passes
  },
  { _id: false },
);

/** Cards are fully embedded — _id is auto-generated by Mongoose.
 *  Referenced externally by calendarEvents.linkedCardId. */
const CardSchema = new Schema<ICard>(
  {
    title: { type: String, required: true, trim: true },
    description: { type: String, default: '' },
    priority: {
      type: String,
      enum: ['low', 'medium', 'high', 'urgent'],
      default: null,
    },
    order: { type: Number, required: true },
    tags: { type: [TagSchema], default: [] },
    dueDate: { type: Date, default: null },

    // Optional bidirectional link to a calendar event
    linkedEventId: {
      type: Schema.Types.ObjectId,
      ref: 'CalendarEvent',
      default: null,
    },

    notifications: { type: CardNotificationsSchema, default: null },
  },
  {
    timestamps: true, // createdAt + updatedAt per card
  },
);

/** Columns hold their cards inline. id is a stable client string (not
 *  MongoDB ObjectId) so drag-and-drop reorder doesn't need DB ids. */
const ColumnSchema = new Schema<IColumn>(
  {
    id: { type: String, required: true },
    name: { type: String, required: true, trim: true },
    order: { type: Number, required: true },
    cards: { type: [CardSchema], default: [] },
  },
  { _id: false }, // columns are positionally identified by their id field
);

// ─────────────────────────────────────────────
// Root schema
// ─────────────────────────────────────────────

const BoardSchema = new Schema<IBoard>(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    name: { type: String, required: true, trim: true },
    columns: { type: [ColumnSchema], default: [] },
  },
  {
    timestamps: true,
  },
);

// ─────────────────────────────────────────────
// Indexes
// ─────────────────────────────────────────────

BoardSchema.index({ userId: 1 });
// Enables calendar view: find all boards with cards that have due dates
BoardSchema.index({ 'columns.cards.dueDate': 1 });

// ─────────────────────────────────────────────
// Export
// ─────────────────────────────────────────────

export const Board = model<IBoard>('Board', BoardSchema);
